// Config for verifier A2. Reads from an env-like object (process.env locally,
// the Worker `env` binding on Cloudflare). In MODE=mock it falls back to embedded
// DEV-ONLY keys so the e2e harness runs with zero setup. NEVER ship mock mode.
//
// Secrets (ADR 0003): PEPPER and SIGNER_KEY must live behind a KMS/HSM boundary in
// production. The raw OIB is hashed the instant it arrives and never logged/stored.

export type EnvLike = Record<string, string | undefined>;

// DEV-ONLY defaults (generated by scripts/genkey.ts). Reproducible so the mock
// issuer and verifier agree without any wiring. Do not use outside local dev.
const DEV_MOCK_ISSUER_JWK =
  '{"crv":"Ed25519","d":"0MuSHfmAkduvfrvACr15GbH7dOSnk38F1hiyARk_00Q","kty":"OKP","x":"yeDNFj9aI_Uu2K-h1J4dtiIBlNiZ5Iihf6U6Fp0voFw","kid":"mock-issuer-1","alg":"EdDSA"}';
const DEV_SIGNER_KEY = "0xe44d2b21a073de42c0d1f91441635b0e3c94825f37d2b3115c038bffa9435ff6";
// signer address for the key above (addSigner this on EIP712Verifier):
export const DEV_SIGNER_ADDRESS = "0xd4739c08DF98C20C7861373c6aE0A44D604061D5";
const DEV_PEPPER = "airkuna-mvp-dev-pepper-DO-NOT-USE-IN-PROD";

export const MOCK_ISSUER_URL = "https://mock-issuer.airkuna.local";
export const MOCK_AUDIENCE = "airkuna-mvp";

export interface Config {
  mode: "mock" | "prod";
  pepper: string;
  signerKey: `0x${string}`;
  chainId: number;
  verifyingContract?: `0x${string}`;
  attestationTtlSec: number;
  // prod (Certilia)
  certiliaIssuer: string;
  certiliaClientId?: string;
  // mock
  mockIssuerJwk: string;
}

function req(env: EnvLike, key: string, fallback?: string): string {
  const v = env[key] ?? fallback;
  if (v === undefined) throw new Error(`missing_env:${key}`);
  return v;
}

export function loadConfig(env: EnvLike): Config {
  const mode = (env.MODE ?? "mock") === "prod" ? "prod" : "mock";
  const dev = mode === "mock";

  const vc = env.VERIFYING_CONTRACT;
  return {
    mode,
    pepper: req(env, "PEPPER", dev ? DEV_PEPPER : undefined),
    signerKey: req(env, "SIGNER_KEY", dev ? DEV_SIGNER_KEY : undefined) as `0x${string}`,
    chainId: Number(env.CHAIN_ID ?? 10200), // Gnosis Chiado
    verifyingContract: vc ? (vc as `0x${string}`) : undefined,
    attestationTtlSec: Number(env.ATTESTATION_TTL_SEC ?? 600),
    certiliaIssuer: env.CERTILIA_ISSUER ?? "https://idp.certilia.com",
    certiliaClientId: env.CERTILIA_CLIENT_ID,
    mockIssuerJwk: req(env, "MOCK_ISSUER_JWK", dev ? DEV_MOCK_ISSUER_JWK : undefined),
  };
}

// eIDAS acr → level of assurance. Certilia may send a URI or a bare label.
export function acrToLoa(acr: unknown): number {
  const s = String(acr ?? "").toLowerCase();
  if (s.includes("high")) return 3;
  if (s.includes("substantial")) return 2;
  if (s.includes("low")) return 1;
  // numeric acr already?
  const n = Number(acr);
  if (Number.isInteger(n) && n >= 1 && n <= 3) return n;
  return 3; // mock issuer asserts eIDAS High
}
